






















project.afterEvaluate {
    def archList = ["x86", "x86_64"]

    
    def configurePrefabForTask = { taskName, arch, dirName, abiName ->
        def task = tasks.findByName("${taskName}[$arch]")
        if (task != null) {
            task.doFirst {
                def prefabPackageFiles = abi.variant.prefabPackages.files
                for (File file : prefabPackageFiles) {
                    def libsDir = findFirstLibsSubdirectory(file)
                    def libsArchDir = new File(libsDir, dirName)
                    if (!libsArchDir.exists()) {
                        libsArchDir.mkdirs()
                        def abiJsonFile = new File(libsArchDir, "abi.json")
                        def abiContent = """
                            {
                              "abi": "$abiName",
                              "api": 16,
                              "ndk": 23,
                              "stl": "none",
                              "static": false
                            }""".stripIndent()
                        abiJsonFile.write(abiContent)
                        def dummySoFile = new File(libsArchDir, "libshadowhook.so")
                        dummySoFile.createNewFile()
                    }
                }
            }
        }
    }

    
    def variants = ["Debug", "Release", "RelWithDebInfo", "Proguard", "ProguardNoDebug", "Gplay"]
    for(arch in archList) {
        def abiName = "$arch"
        def dirName = "android.$arch"
        for(variant in variants) {
            configurePrefabForTask("configureCMake${variant}", arch, dirName, abiName)
            configurePrefabForTask("configureNdkBuild${variant}", arch, dirName, abiName)
        }
    }
}

def findFirstLibsSubdirectory(File baseDir) {
    
    if (!baseDir.exists() || !baseDir.isDirectory()) {
        throw new IllegalArgumentException("baseDir not exists: $baseDir")
    }
    def result = null
    baseDir.eachFileRecurse(groovy.io.FileType.DIRECTORIES) { dir ->
        if (dir.name == 'libs') {
            result = dir
            return true
        }
    }
    return result
}
