plugins {
    id 'java'
}
def lwjglVersion = "3.3.3"
group = 'org.lwjgl.glfw'

configurations {
    lwjglModules {
        canBeResolved = true
    }
}

dependencies {
    implementation fileTree(dir: "libs/lwjgl-$lwjglVersion", include: ['*.jar'])
    lwjglModules fileTree(dir: "libs/lwjgl-$lwjglVersion", include: ['*.jar'])
}

jar {
    
    String[] excludedModules = [
            "jsr305.jar",
            "lwjgl.jar",
            "lwjgl-freetype.jar",

            "lwjgl-lwjglx.jar",
            "lwjgl-jemalloc.jar",
            "lwjgl-nanovg.jar",
            "lwjgl-openal.jar",

            "lwjgl-sdl.jar",
            "lwjgl-shaderc.jar",
            "lwjgl-spng.jar",
            "lwjgl-spvc.jar",
            "lwjgl-stb.jar",
            "lwjgl-tinyfd.jar",
            "lwjgl-vma.jar",
            "lwjgl-vulkan.jar",
    ]

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveBaseName.set("lwjgl-${lwjglVersion}-merged-modules")

    destinationDirectory = file("${project(':app_pojavlauncher').layout.projectDirectory}/src/main/assets/components/lwjgl3/${lwjglVersion}")

    from {
        
        
        
        def includedModules = configurations.lwjglModules.findAll { dep ->
            !excludedModules.any { it == dep.name }
        }
        def coreJar = includedModules.find { it.name == "lwjgl.jar" }
        def jarList = [coreJar] + (includedModules - coreJar)
        if (coreJar == null) jarList = jarList - coreJar
        println("Merging LWJGL $lwjglVersion modules in the order: ")
        (jarList).collect {
            println(it.getName())
            it.isDirectory() ? it : zipTree(it)
        }
    }
    
    preserveFileTimestamps = false
    reproducibleFileOrder = true

    def versionFile = new File(destinationDirectory.get().asFile, "version")
    def jarFile = archiveFile.get().asFile
    doLast {
        def excludedModulesFileList = excludedModules.collectMany { fileName ->
            configurations.lwjglModules.findAll { it.name == fileName }
        }
        copy {
            
            from excludedModulesFileList
            into archiveFile.get().asFile.parentFile
        }
        writeVersionFile([jarFile] as File[] + excludedModulesFileList, versionFile)
    }
    
    outputs.file(versionFile)
    outputs.files excludedModules.collect { path -> new File(destinationDirectory.get().asFile, path) }





    exclude 'net/java/openjdk/cacio/ctc/**'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

